{{- $targetAppName := "workerapp" -}}
{{- $targetNamespace := .Values.spec.source.targetRevision -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $targetAppName }}
  labels:
    app: {{ $targetAppName }}
    env: {{ $targetNamespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ $targetNamespace }}
    server: {{ .Values.spec.destination.server }}
  source:
    path: helm/workerapp
    repoURL: "{{ .Values.spec.source.repoURL }}"
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      valueFiles:
        - values.yaml
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

