apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ printf "%s-pv" (include "postgresdb.fullname" .) }}
spec:
  capacity:
    storage: {{ .Values.pv.storage }}
  volumeMode: Filesystem
  accessModes:
    - {{ .Values.pv.accessModes | quote }}
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "{{ .Values.pv.hostPath }}"
