apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-secret" (include "postgresdb.fullname" .) }}
  labels:
    {{- include "postgresdb.labels" . | nindent 4 }}
type: Opaque
metadata:
  name: {{ include "postgresdb.fullname" . }} 
data:
  {{- with .Values.env }}
    {{- toYaml .| nindent 2 }}
  {{- end }} 