apiVersion: v1
kind: Service
metadata:
  name: {{ include "resultapp.fullname" . }}
  labels:
    {{- include "resultapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      nodePort: {{ .Values.service.nodePort }}
      name: http
  selector:
    {{- include "resultapp.selectorLabels" . | nindent 4 }}
